apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  # optional if you apply with -n ecom
  namespace: ecom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # optional; let the cluster default pick the StorageClass
  # storageClassName: managed-csi
